version: '2'

services:

  socks-proxy:
    # https://github.com/weaveworks/build-tools/blob/master/socks/Dockerfile 
    image: weaveworks/socksproxy
    restart: always
    ports:
      - 127.0.0.1:9050:8000
    logging:
      options:
        max-size: 50m

  nodepki:
    image: adito/nodepki-docker
    volumes:
      - nodepki-certs-nexus:/certs/nexus
      - nodepki-certs-rabbitmq:/certs/rabbitmq
      - nodepki-certs-graylog:/certs/graylog
      - nodepki-certs-gitlab:/certs/gitlab
      - nodepki-certs-project:/certs/project

      - nodepki-data:/root/nodepki/data
      - nodepki-data:/root/nodepki-client/data
      - nodepki-data:/root/nodepki-webclient/data

      - ./docker-nodepki/applications/nodepki/data/config:/root/nodepki/data/config
      - ./docker-nodepki/applications/nodepki-client/data/config:/root/nodepki-client/data/config
      - ./docker-nodepki/applications/nodepki-webclient/data/config:/root/nodepki-webclient/data/config
      - ./docker-nodepki/applications/nodepki-webclient/api/webclient/controllers/request.js:/root/nodepki-webclient/controllers/request.js
    environment:
      - API_USERNAME=admin
      - API_PASSWORD=admin
    logging:
      options:
        max-size: 50m

  nexus:
    image: clearent/nexus:latest
    restart: always
    volumes:
      - nodepki-certs-nexus:/certs/nexus
      - nexus-data:${NEXUS_DATA}
      - ./etc/nexus/nexus.properties:/opt/sonatype/sonatype-work/nexus3/etc/nexus.properties
    environment:
      - JKS_PASSWORD=${JKS_PASSWORD}
    logging:
      options:
        max-size: 50m

  elasticsearch-master:
    image: "elasticsearch:2"
    restart: always
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - graylog-master-data:/usr/share/elasticsearch/data
    environment:
      - MAX_OPEN_FILES=65535
      - MAX_LOCKED_MEMORY=unlimited
      - ES_JAVA_OPTS=-server
    logging:
      options:
        max-size: 50m

  elasticsearch-node01:
    image: marcelmaatkamp/alpine-elasticsearch
    restart: always
    command: --Ecluster.name=graylog --Enode.name=elasticsearch-node01 --Ediscovery.zen.ping.unicast.hosts=master:9300 --Enetwork.host=elasticsearch-node01 --Ees.network.bind_host=elasticsearch-node01
    hostname: elasticsearch-node01
    links:
      - "elasticsearch-master:master"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - MAX_OPEN_FILES=65535
      - MAX_LOCKED_MEMORY=unlimited
      - ES_JAVA_OPTS=-server
    logging:
      options:
        max-size: 50m

  mongodb:
    image: mongo:3
    restart: always
    command: "mongod --smallfiles"
    volumes:
      - mongodb-conf:/etc/mongod.conf:ro
      - mongodb-data:/data/db
    logging:
      options:
        max-size: 50m

  graylog:
    image: "graylog2/server"
    hostname: graylog
    restart: always
    volumes:
      - graylog-data:/usr/share/graylog/data/journal
      - graylog-conf:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: /api
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    links:
      - mongodb:mongo
      - elasticsearch-master:elasticsearch
    logging:
      options:
        max-size: 50m

  rabbitmq:
    image: marcelmaatkamp/rabbitmq-mqtt-ldap
    restart: always
    hostname: rabbitmq
    environment:
      RABBITMQ_NODENAME: rabbitmq@rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
      - ./etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
      - nodepki-certs-rabbitmq:/certs/rabbitmq
    logging:
      options:
        max-size: 50m

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab'
    volumes:
      - 'gitlab-log:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
      - nodepki-certs-gitlab:/etc/gitlab/ssl
    logging:
      options:
        max-size: 50m

  producer:
#   image: nexus:5000/java/spring-boot-example:1.0
    build: project
    environment:
     - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
     - spring.main.web-environment=false
     - spring.profiles.active=test
     - endpoints.jmx.enabled=true
     - spring.application.admin.jmx-port=1099
    volumes:
     - nodepki-certs-project:/usr/local/share/ca-certificates
     - ca-certificates:/usr/share/ca-certificates
    ports:
     - 5005:5005
     - 1099:1099
    logging:
      options:
        max-size: 50m

  compile:
    image: gradle/example
    build:
      context: project
    command: gradle -DsocksProxyHost=docker -DsocksProxyPort=1080 build
    volumes:
     - gradle-cache:/home/gradle/.gradle
     - gradle-cache:/home/gradle/build
     - nodepki-certs-project:/usr/local/share/ca-certificates
     - ca-certificates:/usr/share/ca-certificates

  run:
    image: gradle/example
    build:
     context: project
    command: gradle bootRun
    volumes:
     - gradle-cache:/home/gradle/.gradle
     - gradle-cache:/home/gradle/build
     - nodepki-certs-project:/usr/local/share/ca-certificates
     - ca-certificates:/usr/share/ca-certificates
     
  couchdb:
    image: couchdb
    restart: always
    volumes:
      - couch-data:/opt/couchdb/data
#     - couch-conf:/opt/couchdb/etc
    logging:
      options:
        max-size: 50m

  oracle:
    image: mritschel/oracle12cr2_base
    restart: always
    volumes:
      - oracle-data:/u01/oracle/oradata
    logging:
      options:
        max-size: 50m

  ssl:    
    build:
     context: project
     # buildfile: Dockerfile.ssl
    volumes:
     - ca-certificates:/usr/share/ca-certificates  

  amqp:
    restart: always
    image: marcelmaatkamp/steemit-amqp
    environment:
     - RABBITMQ_HOSTNAME=rabbitmq
     - RABBITMQ_EXCHANGE=amq.topic
    volumes:
     - ./credentials.py:/app/mycredentials.py

  neo4j:
    image: neo4j
    restart: always
    volumes:
     - neo4j-data:/data
     - neo4j-logs:/logs
    logging:
      options:
        max-size: 50m

volumes:
  rabbitmq:

  mongodb-data:
  mongodb-conf:
  graylog-data:
  graylog-master-data:
  graylog-conf:
  elastic-data: 

  gitlab-log:
  gitlab-data:

  nexus-data:

  nodepki-data:
  nodepki-certs-nexus:
  nodepki-certs-rabbitmq:
  nodepki-certs-graylog:
  nodepki-certs-gitlab: 
  nodepki-certs-project: 

  gradle-cache:
  ca-certificates:
  
  couch-data:
  oracle-data:

  neo4j-data:
  neo4j-logs: 
